// ESTIMATION ACTIONS
export const ADD_TICKET = 'ADD_TICKET';
export const DEL_TICKET = 'DEL_TICKET';
export const AVG_VELOCITY = 'AVG_VELOCITY';
export const UPDATE_TICKET = 'UPDATE_TICKET';
export const CALCULATE_RESULTS = 'CALCULATE_RESULTS';
